Update dependency @octokit/rest to v16 (#50)
* Update dependency @octokit/rest to v16

* Fix `Github#getAuthenticatedUser()` method

`users.get` was deprecated in @octokit/rest.js [v15.18.0](https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations)
and removed in [v16.0.1](https://github.com/octokit/rest.js/releases/tag/v16.0.1).

Resolves #32.

* Fix `octokit.authenticate()` deprecation error

Since `@octokit/rest.js` v??, when `octokit.authenticate()` is called,
the following error is logged:

```
Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.
```

I've updated the `Github` class to use the new approach which requires
you to [pass an `auth` option to the Octokit constructor](https://github.com/octokit/rest.js#authentication).

Due to this change and how it affects the usage of the `Github` class
(passing authentication options when creating a `new Github` instance
rather than through a method on an existing `Github` instance), I've
had to make `extractOwnerAndRepo()` a static method. Bah, classes.

* Fix add command test

This test wasn't actually making an assertion against the `addCommand`
object. Whoops.