Fix `octokit.authenticate()` deprecation error
Since `@octokit/rest.js` v??, when `octokit.authenticate()` is called,
the following error is logged:

```
Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.
```

I've updated the `Github` class to use the new approach which requires
you to [pass an `auth` option to the Octokit constructor](https://github.com/octokit/rest.js#authentication).

Due to this change and how it affects the usage of the `Github` class
(passing authentication options when creating a `new Github` instance
rather than through a method on an existing `Github` instance), I've
had to make `extractOwnerAndRepo()` a static method. Bah, classes.